# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test if a target path has xattrs
#'
#' @md
#' @param path target path (file or dir); this is auto-expanded
#' @param follow_symlinks if `FALSE` get xattr of the symlink vs the target it references
#' @export
#' @example inst/examples/ex1.R
has_xattrs <- function(path, follow_symlinks = TRUE) {
    .Call('_xattrs_has_xattrs', PACKAGE = 'xattrs', path, follow_symlinks)
}

rcpp_set_xattr <- function(path, name, value, follow_symlinks = TRUE) {
    .Call('_xattrs_rcpp_set_xattr', PACKAGE = 'xattrs', path, name, value, follow_symlinks)
}

rcpp_rm_xattr <- function(path, name, follow_symlinks = TRUE) {
    .Call('_xattrs_rcpp_rm_xattr', PACKAGE = 'xattrs', path, name, follow_symlinks)
}

rcpp_list_xattrs <- function(path, follow_symlinks = TRUE) {
    .Call('_xattrs_rcpp_list_xattrs', PACKAGE = 'xattrs', path, follow_symlinks)
}

rcpp_get_xattr <- function(path, name, follow_symlinks = TRUE) {
    .Call('_xattrs_rcpp_get_xattr', PACKAGE = 'xattrs', path, name, follow_symlinks)
}

rcpp_get_xattr_raw <- function(path, name, follow_symlinks = TRUE) {
    .Call('_xattrs_rcpp_get_xattr_raw', PACKAGE = 'xattrs', path, name, follow_symlinks)
}

rcpp_get_xattr_size <- function(path, name, follow_symlinks = TRUE) {
    .Call('_xattrs_rcpp_get_xattr_size', PACKAGE = 'xattrs', path, name, follow_symlinks)
}

rcpp_get_xattr_df <- function(path, follow_symlinks = TRUE) {
    .Call('_xattrs_rcpp_get_xattr_df', PACKAGE = 'xattrs', path, follow_symlinks)
}

