# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test if a target path has a particular xattr
#'
#' @md
#' @param path target path (file or dir); this is auto-expanded
#' @param follow_symlinks if `FALSE` get xattr of the symlink vs the target it references
#' @export
has_xattrs <- function(path, follow_symlinks = TRUE) {
    .Call('_xattrs_has_xattrs', PACKAGE = 'xattrs', path, follow_symlinks)
}

#' List extended attribute names of a target path
#'
#' @md
#' @param path target path (file or dir); this is auto-expanded
#' @param follow_symlinks if `FALSE` get xattr of the symlink vs the target it references
#' @export
list_xattrs <- function(path, follow_symlinks = TRUE) {
    .Call('_xattrs_list_xattrs', PACKAGE = 'xattrs', path, follow_symlinks)
}

#' Retrieve the contents of the named xattr
#'
#' @md
#' @note You should really use [get_xattr_raw()]
#' @param path target path (file or dir); this is auto-expanded
#' @param name xattr name to retrieve
#' @param follow_symlinks if `FALSE` get xattr of the symlink vs the target it references
#' @export
get_xattr <- function(path, name, follow_symlinks = TRUE) {
    .Call('_xattrs_get_xattr', PACKAGE = 'xattrs', path, name, follow_symlinks)
}

#' Retrieve the (raw) contents of the named xattr
#'
#' @md
#' @param path target path (file or dir); this is auto-expanded
#' @param name xattr name to retrieve
#' @param follow_symlinks if `FALSE` get xattr of the symlink vs the target it references
#' @export
get_xattr_raw <- function(path, name, follow_symlinks = TRUE) {
    .Call('_xattrs_get_xattr_raw', PACKAGE = 'xattrs', path, name, follow_symlinks)
}

#' Retrieve the size (bytes) of the named xattr
#'
#' @md
#' @param path target path (file or dir); this is auto-expanded
#' @param name xattr name to retrieve
#' @param follow_symlinks if `FALSE` get xattr of the symlink vs the target it references
#' @export
get_xattr_size <- function(path, name, follow_symlinks = TRUE) {
    .Call('_xattrs_get_xattr_size', PACKAGE = 'xattrs', path, name, follow_symlinks)
}

rcpp_get_xattr_df <- function(path, follow_symlinks = TRUE) {
    .Call('_xattrs_rcpp_get_xattr_df', PACKAGE = 'xattrs', path, follow_symlinks)
}

